version: '3.8'

services:
  sse_app:
    container_name: sse_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://sse_postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ou812
    depends_on:
      - sse_postgres

  sse_postgres:
    container_name: sse_postgres
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ou812
    ports:
      - "5431:5432"
