name: build

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:12-3.2
        env:
          POSTGRES_DB: springtest
          POSTGRES_PASSWORD: ou812
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
        ports:
          # maps tcp port 5432 on service container to the host
          - 5432:5432
        # set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and Test
        run: ./gradlew build

      - name: Archive test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test
          retention-days: 30
